/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuMain;

import Controller.ChuyenManHinhController;
import Login.Login;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import java.lang.String;
import javax.swing.JOptionPane;


/**
 *
 * @author ADMIN
 */
public class MainMenu extends javax.swing.JFrame {
    
    public MainMenu(String taiKhoan) {
        initComponents();
        setTitle("Bán Vé Xe Bus");
        ChuyenManHinhController controler= new ChuyenManHinhController(jpnView);
        controler.setView(jpnVeXe, jlbVeXe,taiKhoan);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icon/bus_16px.png")));
        this.setTitle("Quản lý");
        List<DanhMucBean> listIteam= new ArrayList<>();
//        listIteam.add(new DanhMucBean("TrangChu", jpnTrangChu, jlbTrangChu));
        listIteam.add(new DanhMucBean("NhanVien", jpnNhanVien, jlbNhanVien));
        listIteam.add(new DanhMucBean("ChuyenXe", jpnChuyenXe, jlbChuyenXe));
        listIteam.add(new DanhMucBean("VeXe", jpnVeXe, jlbVeXe));
        listIteam.add(new DanhMucBean("ThongKe", jpnThongKe, jlbThongKe));
        listIteam.add(new DanhMucBean("TuyenXe", jpnTuyenXe, jlbTuyenXe));
        listIteam.add(new DanhMucBean("CaLamViec", jpnCaLamViec, jlbCaLamViec));
        listIteam.add(new DanhMucBean("QuanLy", jpnQuanLy, jlbQuanLy));
        listIteam.add(new DanhMucBean("QuanLyUser", jpnQuanLyUser, jlbQuanLyUser));  
    
        
        controler.setEvent(listIteam,taiKhoan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnNhanVien = new javax.swing.JPanel();
        jlbNhanVien = new javax.swing.JLabel();
        jpnChuyenXe = new javax.swing.JPanel();
        jlbChuyenXe = new javax.swing.JLabel();
        jpnVeXe = new javax.swing.JPanel();
        jlbVeXe = new javax.swing.JLabel();
        jpnThongKe = new javax.swing.JPanel();
        jlbThongKe = new javax.swing.JLabel();
        jpnTuyenXe = new javax.swing.JPanel();
        jlbTuyenXe = new javax.swing.JLabel();
        jpnCaLamViec = new javax.swing.JPanel();
        jlbCaLamViec = new javax.swing.JLabel();
        jpnQuanLy = new javax.swing.JPanel();
        jlbQuanLy = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelHome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlbDangXuat = new javax.swing.JLabel();
        jpnQuanLyUser = new javax.swing.JPanel();
        jlbQuanLyUser = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnRoot.setBackground(new java.awt.Color(54, 33, 89));

        jpnNhanVien.setBackground(new java.awt.Color(54, 33, 89));

        jlbNhanVien.setBackground(new java.awt.Color(54, 33, 89));
        jlbNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jlbNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add_user_male_40px.png"))); // NOI18N
        jlbNhanVien.setText("QUẢN LÝ NHÂN VIÊN");
        jlbNhanVien.setMaximumSize(new java.awt.Dimension(196, 48));
        jlbNhanVien.setMinimumSize(new java.awt.Dimension(196, 48));
        jlbNhanVien.setPreferredSize(new java.awt.Dimension(196, 48));

        jpnChuyenXe.setBackground(new java.awt.Color(54, 33, 89));

        jlbChuyenXe.setBackground(new java.awt.Color(54, 33, 89));
        jlbChuyenXe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbChuyenXe.setForeground(new java.awt.Color(255, 255, 255));
        jlbChuyenXe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbChuyenXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/waypoint_map_40px.png"))); // NOI18N
        jlbChuyenXe.setText("QUẢN LÝ CHUYẾN XE ");
        jlbChuyenXe.setMaximumSize(new java.awt.Dimension(199, 48));
        jlbChuyenXe.setMinimumSize(new java.awt.Dimension(199, 48));
        jlbChuyenXe.setPreferredSize(new java.awt.Dimension(199, 48));

        javax.swing.GroupLayout jpnChuyenXeLayout = new javax.swing.GroupLayout(jpnChuyenXe);
        jpnChuyenXe.setLayout(jpnChuyenXeLayout);
        jpnChuyenXeLayout.setHorizontalGroup(
            jpnChuyenXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChuyenXeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbChuyenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnChuyenXeLayout.setVerticalGroup(
            jpnChuyenXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbChuyenXe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnNhanVienLayout = new javax.swing.GroupLayout(jpnNhanVien);
        jpnNhanVien.setLayout(jpnNhanVienLayout);
        jpnNhanVienLayout.setHorizontalGroup(
            jpnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhanVienLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jpnChuyenXe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnNhanVienLayout.setVerticalGroup(
            jpnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhanVienLayout.createSequentialGroup()
                .addComponent(jlbNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jpnChuyenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnVeXe.setBackground(new java.awt.Color(54, 33, 89));
        jpnVeXe.setPreferredSize(new java.awt.Dimension(243, 67));

        jlbVeXe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbVeXe.setForeground(new java.awt.Color(255, 255, 255));
        jlbVeXe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbVeXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/save_48px.png"))); // NOI18N
        jlbVeXe.setText("QUẢN LÝ VÉ BÁN ");

        javax.swing.GroupLayout jpnVeXeLayout = new javax.swing.GroupLayout(jpnVeXe);
        jpnVeXe.setLayout(jpnVeXeLayout);
        jpnVeXeLayout.setHorizontalGroup(
            jpnVeXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnVeXeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbVeXe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnVeXeLayout.setVerticalGroup(
            jpnVeXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbVeXe, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        jpnThongKe.setBackground(new java.awt.Color(54, 33, 89));

        jlbThongKe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbThongKe.setForeground(new java.awt.Color(255, 255, 255));
        jlbThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/statistics_48px.png"))); // NOI18N
        jlbThongKe.setText("THỐNG KÊ");

        javax.swing.GroupLayout jpnThongKeLayout = new javax.swing.GroupLayout(jpnThongKe);
        jpnThongKe.setLayout(jpnThongKeLayout);
        jpnThongKeLayout.setHorizontalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongKeLayout.createSequentialGroup()
                .addComponent(jlbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnThongKeLayout.setVerticalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpnTuyenXe.setBackground(new java.awt.Color(54, 33, 89));
        jpnTuyenXe.setForeground(new java.awt.Color(0, 102, 153));

        jlbTuyenXe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbTuyenXe.setForeground(new java.awt.Color(255, 255, 255));
        jlbTuyenXe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTuyenXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/journey_management_planning_48px.png"))); // NOI18N
        jlbTuyenXe.setText("QUẢN LÝ TUYẾN XE");

        javax.swing.GroupLayout jpnTuyenXeLayout = new javax.swing.GroupLayout(jpnTuyenXe);
        jpnTuyenXe.setLayout(jpnTuyenXeLayout);
        jpnTuyenXeLayout.setHorizontalGroup(
            jpnTuyenXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTuyenXeLayout.createSequentialGroup()
                .addComponent(jlbTuyenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnTuyenXeLayout.setVerticalGroup(
            jpnTuyenXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTuyenXe, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        jpnCaLamViec.setBackground(new java.awt.Color(54, 33, 89));

        jlbCaLamViec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbCaLamViec.setForeground(new java.awt.Color(255, 255, 255));
        jlbCaLamViec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCaLamViec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/management_48px.png"))); // NOI18N
        jlbCaLamViec.setText("QUẢN LÝ CA LÀM VIỆC");

        javax.swing.GroupLayout jpnCaLamViecLayout = new javax.swing.GroupLayout(jpnCaLamViec);
        jpnCaLamViec.setLayout(jpnCaLamViecLayout);
        jpnCaLamViecLayout.setHorizontalGroup(
            jpnCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCaLamViecLayout.createSequentialGroup()
                .addComponent(jlbCaLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jpnCaLamViecLayout.setVerticalGroup(
            jpnCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbCaLamViec, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        jpnQuanLy.setBackground(new java.awt.Color(54, 33, 89));

        jlbQuanLy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbQuanLy.setForeground(new java.awt.Color(255, 255, 255));
        jlbQuanLy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbQuanLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/maintenance_48px.png"))); // NOI18N
        jlbQuanLy.setText("QUẢN LÝ KHÁC");

        javax.swing.GroupLayout jpnQuanLyLayout = new javax.swing.GroupLayout(jpnQuanLy);
        jpnQuanLy.setLayout(jpnQuanLyLayout);
        jpnQuanLyLayout.setHorizontalGroup(
            jpnQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyLayout.createSequentialGroup()
                .addComponent(jlbQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnQuanLyLayout.setVerticalGroup(
            jpnQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bus_40px.png"))); // NOI18N

        jLabelHome.setBackground(new java.awt.Color(51, 51, 51));
        jLabelHome.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelHome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHome.setText("VEXEBUS");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setAlignmentX(2.0F);
        jSeparator1.setAlignmentY(2.0F);

        jlbDangXuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        jlbDangXuat.setText("Đăng xuất");
        jlbDangXuat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlbDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbDangXuatMouseClicked(evt);
            }
        });

        jpnQuanLyUser.setBackground(new java.awt.Color(54, 33, 89));

        jlbQuanLyUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbQuanLyUser.setForeground(new java.awt.Color(255, 255, 255));
        jlbQuanLyUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbQuanLyUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user_50px.png"))); // NOI18N
        jlbQuanLyUser.setText("QUẢN LÝ NGƯỜI DÙNG");

        javax.swing.GroupLayout jpnQuanLyUserLayout = new javax.swing.GroupLayout(jpnQuanLyUser);
        jpnQuanLyUser.setLayout(jpnQuanLyUserLayout);
        jpnQuanLyUserLayout.setHorizontalGroup(
            jpnQuanLyUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbQuanLyUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnQuanLyUserLayout.setVerticalGroup(
            jpnQuanLyUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbQuanLyUser, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnCaLamViec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnTuyenXe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnVeXe, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jpnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnQuanLyUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1)
                            .addGroup(jpnRootLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelHome))))
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jlbDangXuat)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHome, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jpnVeXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnTuyenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnCaLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnQuanLyUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jlbDangXuat)
                .addGap(51, 51, 51))
        );

        jpnView.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1091, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jpnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(1376, 832));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlbDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbDangXuatMouseClicked
        // TODO add your handling code here:
        int ret= JOptionPane.showConfirmDialog(this, "Ban chac chan muon dang xuat?","Xac nhan",0);

        if(ret == JOptionPane.CANCEL_OPTION){
            return;
        }else if(ret == JOptionPane.OK_OPTION){
            this.dispose();
            //new Login(null, true);

            Login dialog = new Login(new javax.swing.JFrame(), true);
            dialog.setVisible(true);
        }

    }//GEN-LAST:event_jlbDangXuatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlbCaLamViec;
    private javax.swing.JLabel jlbChuyenXe;
    private javax.swing.JLabel jlbDangXuat;
    private javax.swing.JLabel jlbNhanVien;
    private javax.swing.JLabel jlbQuanLy;
    private javax.swing.JLabel jlbQuanLyUser;
    private javax.swing.JLabel jlbThongKe;
    private javax.swing.JLabel jlbTuyenXe;
    private javax.swing.JLabel jlbVeXe;
    private javax.swing.JPanel jpnCaLamViec;
    private javax.swing.JPanel jpnChuyenXe;
    private javax.swing.JPanel jpnNhanVien;
    private javax.swing.JPanel jpnQuanLy;
    private javax.swing.JPanel jpnQuanLyUser;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnThongKe;
    private javax.swing.JPanel jpnTuyenXe;
    private javax.swing.JPanel jpnVeXe;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
