/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KhachHang;

import Login.Login;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;
import NhanVien.Connect;

/**
 *
 * @author Huu Nhan
 */
public class MuaVe extends javax.swing.JFrame {

    /**
     * Creates new form MuaVe
     */
    public MuaVe(String taiKhoan) {
        initComponents();
        jLabelHello.setText("Huu Nhan");
        layKhachHang(taiKhoan);
        
    }
    void layKhachHang(String taiKhoan){
        
        //jLabelTaiKhoan.setText(taiKhoan);
        Connection ketNoi=Connect.layKetNoi();
        try{
            PreparedStatement ps= ketNoi.prepareStatement("select TenKhachHang,MatKhau\n" +
            "from KhachHang,TaiKhoan \n" +
            "where TaiKhoan.SDT=KhachHang.SDT and KhachHang.TaiKhoan='"+taiKhoan+"'");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                System.out.println("toi day roi");
                //jLabel19.setText(rs.getString(1));
                //System.out.println(rs.getString(1));
                
//                
//                jTextFieldMatKhau.setText(""+rs.getString(2));
            }
        }catch(SQLException e){
            System.out.println("loi lay thong tin de in ");
        }
        
    }
    public void switchPanels(JPanel panel){
        jLayeredPanelMuaVe.removeAll();
        jLayeredPanelMuaVe.add(panel);
        jLayeredPanelMuaVe.repaint();
        jLayeredPanelMuaVe.revalidate();
    }
    void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,118));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(64,43,100));
    }
    int layMaxMaVe(){
        int max=0;
        Connection ketNoi=Connect.layKetNoi();
        try{
            PreparedStatement ps= ketNoi.prepareStatement("select MaVe from Ve");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                if(rs.getInt("MaVe")>=max){
                    max=rs.getInt("MaVe");
                }
            }
        }catch(SQLException e){
            System.out.println("loi lay max ve xe");
        }
        return max;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelList = new javax.swing.JPanel();
        jPanelList1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelList2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelList3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelTaiKhoan = new javax.swing.JLabel();
        jLabelHome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLayeredPanelMuaVe = new javax.swing.JLayeredPane();
        jPanelTimVe = new javax.swing.JPanel();
        jLabelTimVe = new javax.swing.JLabel();
        jTextFieldTimMaVe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelTVMaVe = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelTVMaChuyenXe = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabelTVSoChoDat = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabelTVGia = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabelTVNoiDi = new javax.swing.JLabel();
        jLabelTVNoiDen = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabelTVTK = new javax.swing.JLabel();
        jLabelTVTK1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelMuaVe = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldSoGhe = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxTuyen = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jDateChooserNgay = new com.toedter.calendar.JDateChooser();
        jComboBoxChuyen = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jComboBoxNoiDi = new javax.swing.JComboBox<>();
        jComboBoxNoiDen = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxLoaiVe = new javax.swing.JComboBox<>();
        jPanelTaiKhoan = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldMatKhau = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabelHello = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(54, 33, 89));
        jLabel1.setText("Xin chào,");

        jPanelList.setBackground(new java.awt.Color(54, 33, 89));
        jPanelList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelList1.setBackground(new java.awt.Color(64, 43, 100));
        jPanelList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelList1MousePressed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Đặt vé");

        javax.swing.GroupLayout jPanelList1Layout = new javax.swing.GroupLayout(jPanelList1);
        jPanelList1.setLayout(jPanelList1Layout);
        jPanelList1Layout.setHorizontalGroup(
            jPanelList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelList1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanelList1Layout.setVerticalGroup(
            jPanelList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelList.add(jPanelList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, 40));

        jPanelList2.setBackground(new java.awt.Color(85, 65, 118));
        jPanelList2.setPreferredSize(new java.awt.Dimension(79, 40));
        jPanelList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelList2MousePressed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tìm vé");

        javax.swing.GroupLayout jPanelList2Layout = new javax.swing.GroupLayout(jPanelList2);
        jPanelList2.setLayout(jPanelList2Layout);
        jPanelList2Layout.setHorizontalGroup(
            jPanelList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelList2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanelList2Layout.setVerticalGroup(
            jPanelList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelList.add(jPanelList2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 210, 40));

        jPanelList3.setBackground(new java.awt.Color(85, 65, 118));
        jPanelList3.setPreferredSize(new java.awt.Dimension(79, 40));
        jPanelList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelList3MousePressed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tài khoản");

        javax.swing.GroupLayout jPanelList3Layout = new javax.swing.GroupLayout(jPanelList3);
        jPanelList3.setLayout(jPanelList3Layout);
        jPanelList3Layout.setHorizontalGroup(
            jPanelList3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelList3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanelList3Layout.setVerticalGroup(
            jPanelList3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelList.add(jPanelList3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Đăng xuất");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanelList.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabelTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        jPanelList.add(jLabelTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 180, 20));

        jLabelHome.setBackground(new java.awt.Color(51, 51, 51));
        jLabelHome.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelHome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHome.setText("VEXEBUS");
        jPanelList.add(jLabelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        jPanelList.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 160, 10));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("co du lieu truoc");
        jPanelList.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 200, 20));

        jLayeredPanelMuaVe.setBackground(new java.awt.Color(255, 0, 255));
        jLayeredPanelMuaVe.setLayout(new java.awt.CardLayout());

        jPanelTimVe.setBackground(new java.awt.Color(204, 255, 204));

        jLabelTimVe.setText("Tìm mã vé");
        jLabelTimVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTimVeMouseClicked(evt);
            }
        });

        jLabel5.setText("Mã vé:");

        jLabel16.setText("Mã chuyến xe:");

        jLabel26.setText("Số chỗ đặt:");

        jLabel28.setText("Giá:");

        jLabel30.setText("Nơi đi:");

        jLabel33.setText("Nơi đến:");

        jLabel34.setText("Email:");

        jLabel4.setText("Loại vé:");

        javax.swing.GroupLayout jPanelTimVeLayout = new javax.swing.GroupLayout(jPanelTimVe);
        jPanelTimVe.setLayout(jPanelTimVeLayout);
        jPanelTimVeLayout.setHorizontalGroup(
            jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimVeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTimVeLayout.createSequentialGroup()
                        .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTimVeLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabelTVTK1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelTimVeLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTVSoChoDat, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTVMaChuyenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTVGia, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelTimVeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTVNoiDi, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelTimVeLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTVNoiDen, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTVTK, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelTVMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldTimMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(jLabelTimVe)
                .addGap(125, 125, 125))
        );
        jPanelTimVeLayout.setVerticalGroup(
            jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimVeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTimVe)
                    .addComponent(jTextFieldTimMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTVMaVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabelTVMaChuyenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTVSoChoDat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTVGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabelTVNoiDi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTVNoiDen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabelTVTK, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelTimVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabelTVTK1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLayeredPanelMuaVe.add(jPanelTimVe, "card3");

        jPanelMuaVe.setBackground(new java.awt.Color(0, 204, 204));

        jLabel13.setText("Số ghế");

        jLabel14.setText("Chọn tuyến");

        jLabel15.setText("Nơi đi");

        jLabel17.setText("Mua vé");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jComboBoxTuyen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTuyenItemStateChanged(evt);
            }
        });

        jLabel23.setText("Ngay");

        jComboBoxChuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5h", "6h", "7h", "8h", "9h", "10h", "11h", "12h", "13h", "14h", "15h", "16h", "17h", "18h", "19h", "20h" }));

        jLabel24.setText("Chọn chuyến");

        jLabel25.setText("Nơi đến");

        jLabel3.setText("Loại vé");

        jComboBoxLoaiVe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vé sinh viên", "Vé thường" }));

        javax.swing.GroupLayout jPanelMuaVeLayout = new javax.swing.GroupLayout(jPanelMuaVe);
        jPanelMuaVe.setLayout(jPanelMuaVeLayout);
        jPanelMuaVeLayout.setHorizontalGroup(
            jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMuaVeLayout.createSequentialGroup()
                .addGroup(jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMuaVeLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMuaVeLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMuaVeLayout.createSequentialGroup()
                                .addGroup(jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooserNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(jComboBoxNoiDi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxNoiDen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMuaVeLayout.createSequentialGroup()
                                .addGroup(jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelMuaVeLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(92, 92, 92))
                                    .addGroup(jPanelMuaVeLayout.createSequentialGroup()
                                        .addGroup(jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldSoGhe)
                                    .addComponent(jComboBoxTuyen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxChuyen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxLoaiVe, 0, 145, Short.MAX_VALUE))))))
                .addContainerGap(467, Short.MAX_VALUE))
        );
        jPanelMuaVeLayout.setVerticalGroup(
            jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMuaVeLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBoxTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jComboBoxChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBoxNoiDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jComboBoxNoiDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMuaVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jDateChooserNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPanelMuaVe.add(jPanelMuaVe, "card2");

        jPanelTaiKhoan.setBackground(new java.awt.Color(255, 153, 153));

        jLabel18.setText("Mật khẩu");

        jLabel22.setText("Sửa mật khẩu");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTaiKhoanLayout = new javax.swing.GroupLayout(jPanelTaiKhoan);
        jPanelTaiKhoan.setLayout(jPanelTaiKhoanLayout);
        jPanelTaiKhoanLayout.setHorizontalGroup(
            jPanelTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTaiKhoanLayout.createSequentialGroup()
                .addGroup(jPanelTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTaiKhoanLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel18)
                        .addGap(49, 49, 49)
                        .addComponent(jTextFieldMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTaiKhoanLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel22)))
                .addContainerGap(351, Short.MAX_VALUE))
        );
        jPanelTaiKhoanLayout.setVerticalGroup(
            jPanelTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTaiKhoanLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanelTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173)
                .addComponent(jLabel22)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jLayeredPanelMuaVe.add(jPanelTaiKhoan, "card4");

        jLabelHello.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelHello.setForeground(new java.awt.Color(54, 33, 89));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(jLabelHello, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLayeredPanelMuaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(2110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHello, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLayeredPanelMuaVe))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelList, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelList1MousePressed
        // TODO add your handling code here:
        switchPanels(jPanelMuaVe);
        setColor(jPanelList1);
        resetColor(jPanelList2);
        resetColor(jPanelList3);
    }//GEN-LAST:event_jPanelList1MousePressed

    private void jPanelList2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelList2MousePressed
        // TODO add your handling code here:
        switchPanels(jPanelTimVe);
        resetColor(jPanelList1);
        setColor(jPanelList2);
        resetColor(jPanelList3);
    }//GEN-LAST:event_jPanelList2MousePressed

    private void jPanelList3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelList3MousePressed
        // TODO add your handling code here:
        switchPanels(jPanelTaiKhoan);
        resetColor(jPanelList1);
        resetColor(jPanelList2);
        setColor(jPanelList3);
    }//GEN-LAST:event_jPanelList3MousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Login(null, true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // mua ve
        int ret= JOptionPane.showConfirmDialog(this, "Ban chac chan muon mua?","Xac nhan",0);

        if(ret == JOptionPane.CANCEL_OPTION){
            return;
        }else if(ret == JOptionPane.OK_OPTION){

            int tonTaiChuyenXe=0;
            int tongSoChoDat=1;
            String soGhe1= jTextFieldSoGhe.getText();
            int soGhe=Integer.parseInt(soGhe1);
            String email=jLabelTaiKhoan.getText();
            String tuyen=(String) jComboBoxTuyen.getSelectedItem() ;
            String chuyen=(String) jComboBoxChuyen.getSelectedItem();
            String noiDi=(String) jComboBoxNoiDi.getSelectedItem();
            String noiDen=(String) jComboBoxNoiDen.getSelectedItem();
            String loaiVe1=(String) jComboBoxLoaiVe.getSelectedItem();
            String maLoaiVe="";
            //lay thong tin loai ve
            if(loaiVe1.equals("Vé sinh viên")){
                maLoaiVe="VSV";
            }else if(loaiVe1.equals("Vé thường")){
                maLoaiVe="VT";
            }
            //=========================

            float gia;
            if(jComboBoxLoaiVe.getSelectedItem().equals("Vé sinh viên")){
                gia=3000;
            }else{
                gia=7000;
            }
            float tongGia=gia*soGhe;
            //Date ngay=(Date) jDateChooserNgay.getDate();

            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            String date=sdf.format(jDateChooserNgay.getDate());
            System.out.println(date);
            // lay ma chuyen
            String year=date.substring(2, 4);
            String month=date.substring(5, 7);
            String day=date.substring(8, 10);
            System.out.println(year+"-"+month+"-"+day);

            String maChuyen=day+month+year+"-"+chuyen+"-"+tuyen;
            System.out.println(maChuyen);
            //lay ma ve
            int maVe=layMaxMaVe()+1;
            //kiem tra chuyen

            Connection ketNoi=Connect.layKetNoi();
            try{
                PreparedStatement ps= ketNoi.prepareStatement("select MaChuyenXe,TongSoChoDat from ChuyenXe");
                ResultSet rs=ps.executeQuery();
                while(rs.next()){
                    if(rs.getString("MaChuyenXe").equalsIgnoreCase(maChuyen)){
                        tongSoChoDat=rs.getInt("TongSoChoDat")+soGhe;
                        tonTaiChuyenXe=1;
                    }
                }
            }catch(SQLException e){
                System.out.println("loi lay tuyen");
            }
            if(tonTaiChuyenXe==0){
                try{
                    PreparedStatement ps= ketNoi.prepareStatement("insert into ChuyenXe values(?,?,?,?)");
                    ps.setString(1, maChuyen);
                    ps.setString(2, tuyen);
                    ps.setInt(3, tongSoChoDat);
                    ps.setString(4, date);
                    ps.executeUpdate();
                }catch(SQLException e){
                    System.out.println("loi luu chuyen xe");
                }
            }
            //lay tong so cho dat

            //muaVe(maChuyen,maVe,soGhe,maLoaiVe,noiDi,noiDen,email,tongGia);
            
            //muaVe(String maChuyen,String maVe,int soChoDat,String NoiDi,String NoiDen,String email,float gia)
            JOptionPane.showMessageDialog(this, "Mua thanh cong! Ma ve cua ban la:"+maVe+".");

        }

    }//GEN-LAST:event_jLabel17MouseClicked

    private void jComboBoxTuyenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTuyenItemStateChanged
        // TODO add your handling code here:
        jComboBoxNoiDi.removeAll();
        jComboBoxNoiDen.removeAll();
        Connection ketNoi=Connect.layKetNoi();
        try{
            PreparedStatement ps= ketNoi.prepareStatement("select Tram from TuyenTram where Tuyen='"+jComboBoxTuyen.getSelectedItem()+"'");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                jComboBoxNoiDi.addItem(rs.getString("Tram"));
                jComboBoxNoiDen.addItem(rs.getString("Tram"));
            }
        }catch(SQLException e){
            System.out.println("loi lay tram");
        }

    }//GEN-LAST:event_jComboBoxTuyenItemStateChanged

    private void jLabelTimVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTimVeMouseClicked
        // TODO add your handling code here:
        Connection ketNoi=Connect.layKetNoi();
        try{
            PreparedStatement ps= ketNoi.prepareStatement("select * from Ve where MaVe='"+jTextFieldTimMaVe.getText()+"'");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                jLabelTVMaVe.setText(rs.getString(1));
                jLabelTVMaChuyenXe.setText(rs.getString(2));
                jLabelTVSoChoDat.setText(rs.getString(3));
                jLabelTVGia.setText(rs.getString(4));
                jLabelTVNoiDi.setText(rs.getString(5));
                jLabelTVNoiDen.setText(rs.getString(6));
                jLabelTVTK.setText(rs.getString(7));
                jLabelTVTK1.setText(rs.getString(8));
            }
        }catch(SQLException e){
            System.out.println("loi lay tuyen");
        }
    }//GEN-LAST:event_jLabelTimVeMouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        String matKhau=jTextFieldMatKhau.getText().trim();
        if(matKhau==""){
            JOptionPane.showMessageDialog(this, "Thong tin rong");
            return;
        }
        Connection ketNoi=Connect.layKetNoi();
        try{
            PreparedStatement ps= ketNoi.prepareStatement("update TaiKhoan set pass='"+matKhau+"' where TaiKhoan='"+jLabelTaiKhoan.getText()+"'");

            ps.executeUpdate();
        }catch(SQLException e){
            System.out.println("loi luu thay doi thong tin TK");
        }

    }//GEN-LAST:event_jLabel22MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuaVe("empty").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxChuyen;
    private javax.swing.JComboBox<String> jComboBoxLoaiVe;
    private javax.swing.JComboBox<String> jComboBoxNoiDen;
    private javax.swing.JComboBox<String> jComboBoxNoiDi;
    private javax.swing.JComboBox<String> jComboBoxTuyen;
    private com.toedter.calendar.JDateChooser jDateChooserNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelHello;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelTVGia;
    private javax.swing.JLabel jLabelTVMaChuyenXe;
    private javax.swing.JLabel jLabelTVMaVe;
    private javax.swing.JLabel jLabelTVNoiDen;
    private javax.swing.JLabel jLabelTVNoiDi;
    private javax.swing.JLabel jLabelTVSoChoDat;
    private javax.swing.JLabel jLabelTVTK;
    private javax.swing.JLabel jLabelTVTK1;
    private javax.swing.JLabel jLabelTaiKhoan;
    private javax.swing.JLabel jLabelTimVe;
    private javax.swing.JLayeredPane jLayeredPanelMuaVe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelList;
    private javax.swing.JPanel jPanelList1;
    private javax.swing.JPanel jPanelList2;
    private javax.swing.JPanel jPanelList3;
    private javax.swing.JPanel jPanelMuaVe;
    private javax.swing.JPanel jPanelTaiKhoan;
    private javax.swing.JPanel jPanelTimVe;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldMatKhau;
    private javax.swing.JTextField jTextFieldSoGhe;
    private javax.swing.JTextField jTextFieldTimMaVe;
    // End of variables declaration//GEN-END:variables
}
